import { UntypedFormControl } from '@angular/forms';
import { SafeHtml, SafeUrl } from '@angular/platform-browser';
import { Observable } from 'rxjs';
import { FormFieldType } from '../../enums/form-field-type';
import { SelectOption } from '../select-option';
import { FormActionConfig } from './form-action-config';
import { FormBannerConfig } from './form-banner-config';
import { FormIncrementerConfig } from './form-incrementer-config';
import { FormInjectableFormFieldConfig } from './form-injectable-form-field-config';
import { FormMultifieldConfig } from './form-multifield-config';
import { FormMultiselectConfig } from './form-multiselect-config';
import { FormNumberConfig } from './form-number-config';
import { FormRatingConfig } from './form-rating-config';
import { FormTextlistConfig } from './form-textlist-config';
import { FormTypeaheadConfig } from './form-typeahead-config';
export class FormFieldVariables {
  public control: UntypedFormControl;
  public controlName: string;
  public type: FormFieldType;
  public id: number;
  public selectOptions: SelectOption<any>[];
  public labelIcon?: SafeHtml;
  public placeholder?: string;
  public isHidden?: boolean;
  public isInlineField?: boolean;
  public maxLength?: number;
  public required?: boolean;
  public label?: string;
  public patternErrorMessage?: string;
  public typeaheadConfig?: FormTypeaheadConfig;
  public dateOptions?: object;
  public multiselectOptions?: {
    groupName: string;
    options: SelectOption<any>[];
  }[];
  public multiselectDefaultOptions?: SelectOption<any>[];
  public textlist?: string[];
  public textlistConfig?: FormTextlistConfig;
  public flexBasisPct?: number;
  public flexGrow?: number;
  public descriptionText?: string;
  public fullLength?: boolean;
  public trackId: string;
  public multifieldConfig?: FormMultifieldConfig;
  public multiselectConfig?: FormMultiselectConfig;
  public imageUrl?: SafeUrl;
  public actionConfig?: FormActionConfig;
  public bannerConfig?: FormBannerConfig;
  public message?: string;
  public disabled = false;
  public isEditable?: boolean;
  public confirmationObsv?: Observable<any>;
  public handleConfirmation?: (event: any) => void;
  public injectableConfig?: FormInjectableFormFieldConfig;
  public hyperlinkTarget?: string;
  public numberConfig?: FormNumberConfig;
  public showLabelInRequiredErrorMessage?: boolean;
  public readOnly?: boolean;
  public ratingConfig?: FormRatingConfig;
  public incrementerConfig?: FormIncrementerConfig;
}
